
server:
  port: 8089

spring:
  application:
    name: client
  redis:
    port: 6379
    host: 127.0.0.1
    password: 1124
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
  mvc:
    static-path-pattern: /static/**

  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl: #\u6CE8\u518C\u4E2D\u5FC3\u7684\u6CE8\u518C\u5730\u5740
      defaultZone: http://127.0.0.1:8080/eureka/
logging:
  file:
    path: spring
feign:
  httpclient:
    enabled: true